name: Jonathan McGuinness
favicon: null
layout_spectrum: 0.7015452468767762
typography_spectrum: 0.21374200307764113
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.6813110071234405
  lightness: 0.5446034404449165
  saturation: 0.6920907939784229
  rhythmicContrast: 0.4865034136455506
purpose: []
